# Generated by Django 4.2.2 on 2023-07-14 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0005_income_person_alter_income_incdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='incDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 14, 1, 32, 16, 403538)),
        ),
    ]
