# Generated by Django 4.2.2 on 2023-07-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0007_alter_income_incdate_alter_income_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.RemoveField(
            model_name='income',
            name='incDate',
        ),
        migrations.AlterField(
            model_name='income',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pluses', to='incomes.appusers'),
        ),
    ]
