# Generated by Django 4.2.2 on 2023-07-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0009_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='incAmount',
            new_name='expAmount',
        ),
    ]
