# Generated by Django 4.2.2 on 2023-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0012_alter_expense_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='transaction_date',
            field=models.DateTimeField(default=None),
        ),
    ]
