# Generated by Django 4.2.2 on 2023-07-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incomes', '0014_alter_expense_created_at_alter_expense_updates_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pluses', to=settings.AUTH_USER_MODEL),
        ),
    ]
