# Generated by Django 4.2.2 on 2023-07-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0015_alter_expense_person_alter_income_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='transaction_category',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='IN', max_length=2),
        ),
    ]
