# Generated by Django 4.2.2 on 2023-07-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0016_income_transaction_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUsers',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
