# Generated by Django 4.2.2 on 2023-07-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0017_delete_appusers_delete_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='transaction_category',
            field=models.CharField(choices=[('1', 'INCOME - Wages'), ('2', 'INCOME - Salary'), ('3', 'INCOME - Commission'), ('4', 'INCOME - Interest'), ('5', 'INCOME - Sale Profit'), ('6', 'INCOME - Investments'), ('7', 'INCOME - Gifts'), ('8', 'INCOME - Allowance/Pocket Money'), ('9', 'INCOME - Government Payments'), ('10', 'INCOME - Other'), ('11', 'EXPENSE - Housing'), ('12', 'EXPENSE - Utilities'), ('13', 'EXPENSE - Vehicles/transportation'), ('14', 'EXPENSE - Gas'), ('15', 'EXPENSE - Groceries/essentials'), ('16', 'EXPENSE - Internet/cable'), ('17', 'EXPENSE - Cellphone'), ('18', 'EXPENSE - Debt payments'), ('19', 'EXPENSE - Memberships and subscriptions '), ('20', 'EXPENSE - Child care'), ('21', 'EXPENSE - Health care'), ('22', 'EXPENSE - Emergency fund'), ('23', 'EXPENSE - Retirement'), ('24', 'EXPENSE - Travel'), ('25', 'EXPENSE - Large purchases'), ('26', 'EXPENSE - Other')], default='10', max_length=26),
        ),
    ]
