# Generated by Django 4.2.2 on 2023-07-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0018_alter_income_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
